[webservers]
web-1 ansible_host=62.84.115.238 fqdn=fhmhn5hsdup96cpt3ckl.auto.internal
web-2 ansible_host=93.77.191.138 fqdn=fhm8kmds2f94nqstonkq.auto.internal

[databases]
main ansible_host=111.88.248.25 fqdn=fhm2a35vca0j3brnjk7j.auto.internal
replica ansible_host=111.88.247.62 fqdn=fhmu947gbvd2l4pfhs6h.auto.internal

[storage]
storage ansible_host=178.154.201.7 fqdn=fhms6ml7ch6a2t9utr8h.auto.internal
